name: ms_string_utils
description: A lot utils functions to improve your work with Strings, with support dart extensions.
version: 0.1.0
author:
homepage: https//github.com/Marcus-Software/ms_string_utils

environment:
  sdk: ">=2.7.0 <3.0.0"

dev_dependencies:
  test: any

flutter:
